<!--↓左メニュー-->
<div id="leftfortop">
    <h2><a href=/ id="whitelink">TOP</a></h2>
</div>

<div id="left">
    <ul>
        <li><a href="http://www.enpitu.ne.jp/usr10/104435/diary.html" id="greenlink">まゆのぼちぼち日記↓<br>「忘れものから見える「人生模様推理」」</A><br>
        </li>
        <li><A href="http://www1.rocketbbs.com/313/kotoba.html" id="greenlink">ことば探しBBS</A></li>
        <li><a href="/kotoba/view.php" id="categorylink"><b>押してみて！　今日の<br>「ぴったりことば占い」</b></a></li>
        <li><a href="/afm.php" id="greenlink">アファメーションとは？</a></li>
    </ul>
</div>

<div id="leftyomikata">
    <h2><a href="/yomikata/01.php" id="whitelink">本の読み方＆<br>おすすめの本</a></h2>
</div>


<div id="left">
    <ul>
        <li><a href="/yomikata/reading.php?" id="greenlink">今日のおすすめ本↓<br>
                「「夢のリスト」で思いどおりの未来をつくる!」<img src="/img/newgs.gif" alt="" width="27"
                                                height="15" border="0"><br></li>
        <li>
            <A href=http://www.amazon.co.jp/s/ref=nb_ss_b?__mk_ja_JP=%83J%83%5E%83J%83i&url=search-alias%3Dstripbooks&field-keywords=%96%B2%82%F0%82%A9%82%C8%82%A6%82%E9&Go.x=5&Go.y=11
               target=_blank id="greenlink">Amazonで売れている<br>
                「読むだけでも楽しい！《夢をかなえる》本」</a><img src="/img/newgs.gif" alt="" width="27"
                                                  height="15" border="0"></li>
        <br>


        <li><A href=http://astore.amazon.co.jp/aaaaea00-22 target=_blank id="greenlink">おすすめ本集↓<br>
                「自分にプレゼントしてみませんか？元気がもらえる９冊」</a></li>
        <br>


    </ul>
</div>


<div id="searchwords">
    <h2><a href="/kotoba/list.php" id="whitelink">今日のことば検索</a></h2>
</div>
<div id="left">


    <ul>

        <li><a href="/kotoba/vest5.php" id="categorylink"><b>「１２月」の人気ことば<br>　ベスト５！</b> </a><img
                    src="/img/newgs.gif" alt="" width="27"
                    height="15" border="0"></li>
        <li><a href="/kotoba/mayubest.php" id="categorylink"><b>2006年「今日のことば」まゆのベスト10</b></a></li>

        <li><a href="/kotoba/calendar.php" id="categorylink"><b>日付順で見る<br>（過去のことば）</b></a></li>
        <li><a href="/kotoba/list.php" id="categorylink"><b>全て見る(※探したい<br>「ことば」はコチラから)</b></a></li>

    </ul>

</div>


<div align="center">
    <form action="/kotoba/list.php" method=get>
        <input name=key type=text size=16 value="<?= isset($_GET['key']) ? $_GET['key'] : ""; ?>" class="nyuryoku">
        <input value=検索 type=submit>
    </form>
</div>


<div id="leftdanjyo">
    <h2><a href="/danjyo/01.php" id="whitelink">必見！本から読み<br>とく「男女の違い」</a></h2>
</div>


<div id="left">
    <ul>
        <li><a href="/danjyo/weekly.php" id="greenlink">男女の違いって？↓<br>「「自分を見つめて、自分の感情を知ろう」…その方法
                」<br>
                <A href="/yomikata/books2.php"><strong>

                        <li><a href="/yomikata/books2.php" id="greenlink">
                                「夫婦関係を考える<br>　おすすめ本３３冊」
                    </strong><A href="/yomikata/books2.php"></A>
                </a></li>
        </li>
    </ul>
</div>


<div id="searchbooks">
    <h2><a href="/book/list.php" id="whitelink">本の検索</a></h2>
</div>


<div align="center">
    <form action="/book/list.php" method=get>
        <input name=key type=text size=16 value="<?= isset($_GET['key']) ? $_GET['key'] : ""; ?>" class="nyuryoku">
        <input value=検索 type=submit>
    </form>
</div>


<!--<div id="leftbosyu">
<h2><a href="#" id="whitelink">募集</a></h2>
</div>
<div id="leftquestion">
<h2><a href="#" id="whitelink">アンケート</a></h2>
</div>-->

<!--↓左メニュー／メールマガジン
<table width="177" border="0" cellspacing="0" cellpadding="0">
<tr>
<td bgcolor="#C8D083">
<div id="leftmagazine">
<h2>メールマガジン</h2>
</div>
</td>
</tr>
<tr>
<td align="center" bgcolor="#C8D083">
<form action="" method="post" target="_blank">
<input name="mail" type="text" size="16" class="nyuryoku">  <input value="購読" type="submit">
<div id="leftnotice">※メールアドレスを<span class="leftnoticekyocyo">半角英数字</span>で入力してください。</div>
</form>
</td>
</tr>
<tr>
<td bgcolor="#C8D083">
</td>
</tr>
<tr>
<td align="right" bgcolor="#C8D083">
<table border="0" cellspacing="5" cellpadding="0">
<tr>
<td><img src="/img/list_imb.gif" alt="" width="5" height="10" border="0"></td>
<td nowrap><a href="#" id="categorylink">雰囲気を見る</a></td>
</tr>
</table>
</td>
</tr>
</table>
↑左メニュー／メールマガジン-->


<div id="left">
    <ul>
        <li><a href="/link.php" id="greenlink">リンク集</a></li>
        <li><a href="/about.php" id="greenlink">このページについて</a></li>
        <li><a href="/owner.php" id="greenlink">主催者について</a>
        <li><a href="/mm.php" id="greenlink">メルマガ登録と解除</a></li>
        <li><a href="/map.php" id="greenlink">サイトマップ</a></li>

    </ul>
</div>

<div id="leftcontact">
    <ul>
        <li><h2><? form_mail("お問合せはこちら"); ?>お問合せ<br>主催者へのメール</a></h2>
        </li>
        <br>
        <li><h2>転載する場合は<br>「ことば探し」の明記<br>お願いいたします。<br>
                転載した場合は、一報<br>頂けますと嬉しいです。<br>無断掲載禁止
            </h2>
        </li>
    </ul>
</div>


<div id="counter">
    <img src="/img/cnt_left.gif" alt="" width="14" height="40" border="0"><? make_counter(); ?><img
            src="/img/cnt_righ.gif" alt="" width="39" height="40" border="0">
</div>

<br>

<!--↑左メニュー-->
