<!--↓左メニュー-->
<div id="leftfortop">
<h2><a href=<?= $URL;?> id="whitelink">TOP</a></h2>
</div>

<div id="left">
<ul>

<li><a href="http://www.kotobasagashi.net/watashinoitizi.php" id="greenlink">２０１４年、一歩を踏み<br>出す「私の一字」ＵＰ<br><img src="http://www.kotobasagashi.net/img/newgs.gif" alt="" width="27"
height="15" border="0">参加募集中！</li><br>
</li>
<li><a href="http://kotobasagashi.way-nifty.com/" id="greenlink">ぼちぼち日記↓<br>「■宝くじが当たったらの話し」</A><img src="http://www.kotobasagashi.net/img/newgs.gif" alt="" width="27"
height="15" border="0">
</A></strong></strong><br>
</li>
<li><a href="http://www.kotobasagashi.net/danjyomerumaga.php" id="greenlink">メールマガジン<br>「男女の違い１０５」<br>第１号から最新３５号<br>タイトルと目次</A></strong><br>
</li><br>





<li><a href="http://www.kotobasagashi.net/oraclecards.php" id="greenlink">オラクルカードの<br>ページへようこそ</li>
</li>
<li><a href="http://www.kotobasagashi.net/kamisama.php" id="greenlink">「日本の神様」カードの<br>ページ</li>
</li>




<li><a href="<?= $URL;?>afm.php" id="greenlink">アファメーションとは？</a></li>
<li><a href="http://astore.amazon.co.jp/affirmation-kotobasagashi-22" id="greenlink">アファメーションの効果を上げる本</li><br>
</li>


<li><a href="<?= $URL;?>kotoba/view.php" id="categorylink"><b>押してみて！　今日の<br>「ぴったりことば占い」</b></a></li>
</ul>
</div>

<div id="leftyomikata">
<h2><a href="<?= $URL;?>yomikata/01.php" id="whitelink">本の読み方＆<br>おすすめの本</a></h2>
</div>


<div id="left">
<ul>
<li><a href="http://www.kotobasagashi.net/yomikata/reading.php?" id="greenlink">今日のおすすめ本↓<br></strong>
「はい、息を吐いて。それからゆっくり考えよう」</A><img src="http://www.kotobasagashi.net/img/newgs.gif" alt="" width="27"
height="15" border="0">
</li>


<li><A href=http://astore.amazon.co.jp/word-kotobasagashi-22 target=_blank id="greenlink">世界の名言、おすすめ<br>ことば集本</a></li>
<li><A href=http://astore.amazon.co.jp/affirmation-kotobasagashi-22 target=_blank id="greenlink">アファメーション関連本</a></li>
<li><A href=http://astore.amazon.co.jp/aaaaea00-22 target=_blank id="greenlink">プレゼントにおすすめの本</a></li>
<li><a href="<?= $URL;?>yomikata/books2.php" id="greenlink">
夫婦関係を考える<br>「おすすめ本３３冊」</strong><A href="http://www.kotobasagashi.net/yomikata/books2.php"></A>
<li><a href="http://www.kotobasagashi.net/danjyo/books.php" id="greenlink">男女の違い必読<br>「おすすめ本２０冊」」</A></li>

<br><br>
<SCRIPT charset="utf-8" type="text/javascript" src="http://ws-fe.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&MarketPlace=JP&ID=V20070822%2FJP%2Faaaaea00-22%2F8002%2Fb55f7d11-75e7-4726-9d4b-56bf273bf5d6"> </SCRIPT> <NOSCRIPT><A HREF="http://ws-fe.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&MarketPlace=JP&ID=V20070822%2FJP%2Faaaaea00-22%2F8002%2Fb55f7d11-75e7-4726-9d4b-56bf273bf5d6&Operation=NoScript">Amazon.co.jp ウィジェット</A></NOSCRIPT>


</ul>
</div>


<div id="searchwords">
<h2><a href="<?= $URL;?>kotoba/list.php" id="whitelink">今日のことば検索</a></h2>
</div>
<div id="left">




<ul>

<li><a href="<?= $URL;?>kotoba/vest5.php" id="categorylink"><b>「２０１４年２月」の人気ことばベスト５</b><img src="http://www.kotobasagashi.net/img/newgs.gif" alt="" width="27"height="15" border="0"><a href="http://www.kotobasagashi.net/yomikata/reading.php?" id="greenlink"></a></li>

<li><a href="<?= $URL;?>kotoba/nenkanbest.php" id="categorylink"><b>２０１１年　人気ことばベスト１０</b> </a></li>


<li><a href="<?= $URL;?>kotoba/mayubest.php" id="categorylink"><b>２００９年まゆが選んだことばベスト１０</b></a></li>



<li><a href="<?= $URL;?>kotoba/calendar.php" id="categorylink"><b>日付順で見る<br>（過去のことば）</b></a></li>
<li><a href="<?= $URL;?>kotoba/list.php" id="categorylink"><b>全て見る(※探したい<br>「ことば」はコチラから)</b></a></li>

</ul>

</div>






<div align="center">
<form action="<?= $URL;?>kotoba/list.php" method=get>
<input name=key type=text size=16 value="<?= isset($_GET['key'])?$_GET['key']:"";?>" class="nyuryoku">
<input value=検索 type=submit>
</form>
</div>




<div id="leftdanjyo">
<h2><a href="<?= $URL;?>danjyo/01.php" id="whitelink">必見！本から読み<br>とく「男女の違い」</a></h2>
</div>




<div id="left">
<ul>
<li><a href="<?= $URL;?>danjyo/weekly.php" id="greenlink">男女の違いって？↓<br>「自分を見つめて、自分の感情を知ろう…その方法」
<br>
<A href="http://www.kotobasagashi.net/yomikata/books2.php"><strong>

<li><a href="http://www.kotobasagashi.net/book/list.php?sc=1" id="greenlink">男女・恋愛の本一覧</A></li>
<li><a href="http://www.kotobasagashi.net/book/list.php?sc=2" id="greenlink">愛・夫婦・結婚の本<br>一覧</A></li>






</a></li></li>
</ul>
</div>



<div id="searchbooks">
<h2><a href="<?= $URL;?>book/list.php" id="whitelink">本の検索</a></h2>
</div>


<div align="center">
<form action="<?= $URL;?>book/list.php" method=get>
<input name=key type=text size=16 value="<?= isset($_GET['key'])?$_GET['key']:"";?>" class="nyuryoku">
<input value=検索 type=submit>
</form>
</div>




<!--<div id="leftbosyu">
<h2><a href="#" id="whitelink">募集</a></h2>
</div>
<div id="leftquestion">
<h2><a href="#" id="whitelink">アンケート</a></h2>
</div>-->

<!--↓左メニュー／メールマガジン
<table width="177" border="0" cellspacing="0" cellpadding="0">
<tr>
<td bgcolor="#C8D083">
<div id="leftmagazine">
<h2>メールマガジン</h2>
</div>
</td>
</tr>
<tr>
<td align="center" bgcolor="#C8D083">
<form action="" method="post" target="_blank">
<input name="mail" type="text" size="16" class="nyuryoku">  <input value="購読" type="submit">
<div id="leftnotice">※メールアドレスを<span class="leftnoticekyocyo">半角英数字</span>で入力してください。</div>
</form>
</td>
</tr>
<tr>
<td bgcolor="#C8D083">
</td>
</tr>
<tr>
<td align="right" bgcolor="#C8D083">
<table border="0" cellspacing="5" cellpadding="0">
<tr>
<td><img src="<?= $URL;?>img/list_imb.gif" alt="" width="5" height="10" border="0"></td>
<td nowrap><a href="#" id="categorylink">雰囲気を見る</a></td>
</tr>
</table>
</td>
</tr>
</table>
↑左メニュー／メールマガジン-->


<div id="left">
<ul>
<li><a href="<?= $URL;?>link.php" id="greenlink">リンク集</a>
<li><a href="<?= $URL;?>about.php" id="greenlink">このページについて</a></li><li><a href="<?= $URL;?>owner.php" id="greenlink">主催者について</a>
<li><a href="<?= $URL;?>mm.php" id="greenlink">メルマガ登録と解除</a></li>
<li><a href="<?= $URL;?>map.php" id="greenlink">サイトマップ</a></li>
<li><A href="http://www.chibiao.com/type_n2/nk1/kotobasagashi/" id="greenlink">ことば探しBBS</A></li>
</ul>
</div>

<div id="leftcontact">
<ul>
<li><h2><?form_mail("お問合せはこちら");?>お問合せ<br>主催者へのメール</a></h2>
</li><br>
<li><h2>転載する場合は<br>「ことば探し」の明記<br>お願いいたします。<br>
転載した場合は、<br>ご一報お願いいたします。無断掲載禁止
</h2>
</li>
</ul>
</div>



<div id="counter">
<img src="<?= $URL;?>img/cnt_left.gif" alt="" width="14" height="40" border="0"><?make_counter();?><img src="<?= $URL;?>img/cnt_righ.gif" alt="" width="39" height="40" border="0">
</div>

<br>

<!--↑左メニュー-->
