<table border=0 width=735 cellspacing=0 cellpadding=5><tr><td>&nbsp;</td><td>
<table border=5 width=100% cellspacing=0 cellpadding=5>
  <tr>
    <td colspan=4>
      <a href=<?php echo $URL?>admin/index.php?>管理者メニューTOP
    </td>
    <td><form action=news_list.php method=post>
      <input type=submit value='ニュース'>
    </td></form>
    <td><form action=afm_list.php method=post>
      <input type=submit value='アファメーション'>
    </td></form>
  </tr>
  <tr><form action=enq.php method=post>
    <td>
      <input type=submit value='アンケート結果'>
    </td></form><form action=kc_admit_1_list.php method=get>
    <td>
      <input type=submit value='読者の感想'>
    </td></form><form action=source.php method=post>
    <td>
      <input type=submit value='本の登録'>
      <input type=hidden name=submit value='修正'>
    </td></form><form action=source_list.php method=post>
    <td>
      <input type=submit value='本リスト'>
    </td></form><form action=reading_list.php method=post>
    <td>
      <input type=submit value='今読んでいる本'>
    </td></form><form action=danjyo_list.php method=post>
    <td>
      <input type=submit value='今週の男女の違い'>
    </td></form>
  </tr>
</table>
<table border=5 width=100% cellspacing=0 cellpadding=5>
  <tr>
    <td>
