</main>
<section>
    <p>
        ■ほっこりしたい方、<br>
        ネコ好きさんにおすすめの本。<br><br>
        じいちゃんとタマの関係が<br>
        なんともよく特に１．２は<br>
        おすすめですよ～!!
    </p>
    <a href="https://www.amazon.co.jp/dp/4040676718/ref=nosim?tag=aaaaea00-22" target="_blank">
        <img src="https://images-na.ssl-images-amazon.com/images/P/4040676718.09.LZZZZZZZ.jpg" style="width: 120px;border: 1px solid black">
    </a>
    <a href="https://www.amazon.co.jp/dp/4040683625/ref=nosim?tag=aaaaea00-22" target="_blank">
        <img src="https://images-na.ssl-images-amazon.com/images/P/4040683625.09.LZZZZZZZ.jpg" style="width: 120px;border: 1px solid black">
    </a>
    <a href="https://www.amazon.co.jp/dp/4040690583/ref=nosim?tag=aaaaea00-22" target="_blank">
        <img src="https://images-na.ssl-images-amazon.com/images/P/4040690583.09.LZZZZZZZ.jpg" style="width: 120px;border: 1px solid black">
    </a>
    <a href="https://www.amazon.co.jp/dp/4040697359/ref=nosim?tag=aaaaea00-22" target="_blank">
        <img src="https://images-na.ssl-images-amazon.com/images/P/4040697359.09.LZZZZZZZ.jpg" style="width: 120px;border: 1px solid black">
    </a>
</section>
</div>
<?php
require_once $_SERVER["DOCUMENT_ROOT"] . '/inc/html_foot.inc';
