</main>
<section>
    <p>
        ■ほっこりしたい方、<br>
        ネコ好きさんにおすすめの本。<br><br>
        じいちゃんとタマの関係が<br>
        なんともよく特に１．２は<br>
        おすすめですよ～!!
    </p>
    <iframe style="width:120px;height:240px;" marginwidth="0" marginheight="0" scrolling="no" frameborder="0"
            src="https://rcm-fe.amazon-adsystem.com/e/cm?ref=qf_sp_asin_til&t=aaaaea00-22&m=amazon&o=9&p=8&l=as1&IS2=1&detail=1&asins=4040676718&linkId=05cf66d2c66fcb1b647f18a30bbb97b9&bc1=baf2c5&lt1=_blank&fc1=333333&lc1=0066c0&bg1=baf2c5&f=ifr">
    </iframe>
    <iframe style="width:120px;height:240px;" marginwidth="0" marginheight="0" scrolling="no" frameborder="0"
            src="https://rcm-fe.amazon-adsystem.com/e/cm?ref=qf_sp_asin_til&t=aaaaea00-22&m=amazon&o=9&p=8&l=as1&IS2=1&detail=1&asins=4040683625&linkId=1dd9747e6343edf18572d9a487329475&bc1=baf2c5&lt1=_blank&fc1=333333&lc1=0066c0&bg1=baf2c5&f=ifr">
    </iframe>
    <iframe style="width:120px;height:240px;" marginwidth="0" marginheight="0" scrolling="no" frameborder="0"
            src="https://rcm-fe.amazon-adsystem.com/e/cm?ref=qf_sp_asin_til&t=aaaaea00-22&m=amazon&o=9&p=8&l=as1&IS2=1&detail=1&asins=4040690583&linkId=3b2f30dabed3abe1ca77dca05e75b7f0&bc1=baf2c5&lt1=_blank&fc1=333333&lc1=0066c0&bg1=baf2c5&f=ifr">
    </iframe>
    <iframe style="width:120px;height:240px;" marginwidth="0" marginheight="0" scrolling="no" frameborder="0"
            src="https://rcm-fe.amazon-adsystem.com/e/cm?ref=qf_sp_asin_til&t=aaaaea00-22&m=amazon&o=9&p=8&l=as1&IS2=1&detail=1&asins=4040697359&linkId=75dde725a3e22555cebe09f842d9c326&bc1=baf2c5&lt1=_blank&fc1=333333&lc1=0066c0&bg1=baf2c5&f=ifr">
    </iframe>
</section>
</div>
<?php
require_once $_SERVER["DOCUMENT_ROOT"] . '/inc/html_foot.inc';
