</td>
<td width=11><img src="/img/top_leaw.gif" alt="" width="11" height="46" border="0"/></td></tr>
</table>
<!--↑コンテンツ-->
</td>
<td width="160"><img src="/img/top_leax.gif" alt="" width="21" height="110" border="0"/>
    <br>

    <div align="center"><span class="sidemenu">■ほっこりしたい方、<br>
ネコ好きさんにおすすめの本。<br><br>
じいちゃんとタマの関係が<br>
なんともよく特に１．２は<br>
おすすめですよ～!!<br>　
</span></div>
    <iframe style="width:120px;height:240px;" marginwidth="0" marginheight="0" scrolling="no" frameborder="0"
            src="https://rcm-fe.amazon-adsystem.com/e/cm?ref=qf_sp_asin_til&t=aaaaea00-22&m=amazon&o=9&p=8&l=as1&IS2=1&detail=1&asins=4040676718&linkId=05cf66d2c66fcb1b647f18a30bbb97b9&bc1=baf2c5&lt1=_blank&fc1=333333&lc1=0066c0&bg1=baf2c5&f=ifr">
    </iframe>
    <br>

    <iframe style="width:120px;height:240px;" marginwidth="0" marginheight="0" scrolling="no" frameborder="0"
            src="https://rcm-fe.amazon-adsystem.com/e/cm?ref=qf_sp_asin_til&t=aaaaea00-22&m=amazon&o=9&p=8&l=as1&IS2=1&detail=1&asins=4040683625&linkId=1dd9747e6343edf18572d9a487329475&bc1=baf2c5&lt1=_blank&fc1=333333&lc1=0066c0&bg1=baf2c5&f=ifr">
    </iframe>
    <br>

    <iframe style="width:120px;height:240px;" marginwidth="0" marginheight="0" scrolling="no" frameborder="0"
            src="https://rcm-fe.amazon-adsystem.com/e/cm?ref=qf_sp_asin_til&t=aaaaea00-22&m=amazon&o=9&p=8&l=as1&IS2=1&detail=1&asins=4040690583&linkId=3b2f30dabed3abe1ca77dca05e75b7f0&bc1=baf2c5&lt1=_blank&fc1=333333&lc1=0066c0&bg1=baf2c5&f=ifr">
    </iframe>
    <br>

    <iframe style="width:120px;height:240px;" marginwidth="0" marginheight="0" scrolling="no" frameborder="0"
            src="https://rcm-fe.amazon-adsystem.com/e/cm?ref=qf_sp_asin_til&t=aaaaea00-22&m=amazon&o=9&p=8&l=as1&IS2=1&detail=1&asins=4040697359&linkId=75dde725a3e22555cebe09f842d9c326&bc1=baf2c5&lt1=_blank&fc1=333333&lc1=0066c0&bg1=baf2c5&f=ifr">
    </iframe>
    <br><br>


    <div align="center"><span class="sidemenu">■話題の本、人気本紹介<br></span></div>


    <OBJECT classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000"
            codebase="http://fpdownload.macromedia.com/get/flashplayer/current/swflash.cab"
            id="Player_de079046-84de-4c76-92db-820cc7f63865" WIDTH="160px" HEIGHT="600px">
        <PARAM NAME="movie"
               VALUE="http://ws.amazon.co.jp/widgets/q?ServiceVersion=20070822&MarketPlace=JP&ID=V20070822%2FJP%2Faaaaea00-22%2F8010%2Fde079046-84de-4c76-92db-820cc7f63865&Operation=GetDisplayTemplate">
        <PARAM NAME="quality" VALUE="high">
        <PARAM NAME="bgcolor" VALUE="#FFFFFF">
        <PARAM NAME="allowscriptaccess" VALUE="always">
        <embed src="http://ws.amazon.co.jp/widgets/q?ServiceVersion=20070822&MarketPlace=JP&ID=V20070822%2FJP%2Faaaaea00-22%2F8010%2Fde079046-84de-4c76-92db-820cc7f63865&Operation=GetDisplayTemplate"
               id="Player_de079046-84de-4c76-92db-820cc7f63865" quality="high" bgcolor="#ffffff"
               name="Player_de079046-84de-4c76-92db-820cc7f63865" allowscriptaccess="always"
               type="application/x-shockwave-flash" align="middle" height="600px" width="160px"></embed>
    </OBJECT>
    <NOSCRIPT><A
                HREF="http://ws.amazon.co.jp/widgets/q?ServiceVersion=20070822&MarketPlace=JP&ID=V20070822%2FJP%2Faaaaea00-22%2F8010%2Fde079046-84de-4c76-92db-820cc7f63865&Operation=NoScript">Amazon.co.jp
            ウィジェット</A></NOSCRIPT>
    <br>


    <OBJECT classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000"
            codebase="http://fpdownload.macromedia.com/get/flashplayer/current/swflash.cab"
            id="Player_db988e6d-9ced-4bcd-84af-a7e2c853436e" WIDTH="160px" HEIGHT="600px">
        <PARAM NAME="movie"
               VALUE="http://ws.amazon.co.jp/widgets/q?ServiceVersion=20070822&MarketPlace=JP&ID=V20070822%2FJP%2Faaaaea00-22%2F8010%2Fdb988e6d-9ced-4bcd-84af-a7e2c853436e&Operation=GetDisplayTemplate">
        <PARAM NAME="quality" VALUE="high">
        <PARAM NAME="bgcolor" VALUE="#FFFFFF">
        <PARAM NAME="allowscriptaccess" VALUE="always">
        <embed src="http://ws.amazon.co.jp/widgets/q?ServiceVersion=20070822&MarketPlace=JP&ID=V20070822%2FJP%2Faaaaea00-22%2F8010%2Fdb988e6d-9ced-4bcd-84af-a7e2c853436e&Operation=GetDisplayTemplate"
               id="Player_db988e6d-9ced-4bcd-84af-a7e2c853436e" quality="high" bgcolor="#ffffff"
               name="Player_db988e6d-9ced-4bcd-84af-a7e2c853436e" allowscriptaccess="always"
               type="application/x-shockwave-flash" align="middle" height="600px" width="160px"></embed>
    </OBJECT>
    <NOSCRIPT><A
                HREF="http://ws.amazon.co.jp/widgets/q?ServiceVersion=20070822&MarketPlace=JP&ID=V20070822%2FJP%2Faaaaea00-22%2F8010%2Fdb988e6d-9ced-4bcd-84af-a7e2c853436e&Operation=NoScript">Amazon.co.jp
            ウィジェット</A></NOSCRIPT>


</td>
</tr>
</table>
<!--↑全体-->

<table width="741" border="0"   height="70">
    <tr>
        <td width="190" rowspan="3" valign="bottom"><img src="/img/top_leay2.gif" alt="" width="190"
                                                         height="70" border="0"/></td>
        <td width="275" height="45">
            <div id="topagetop">
                ▼　<a href="/" id="categorylink">「ことば探し」トップページへ</a>
            </div>
        </td>
        <td width="276" height="45">
            <div id="topagetop">
                ▲　<a href="#pagetop" id="categorylink">このページのトップへ</a>
            </div>
        </td>
    </tr>
    <tr>
        <td width="551" height="2" colspan="2">

            <!-- 2009/02/06 広告追加 -->


            <iframe src="http://rcm-fe.amazon-adsystem.com/e/cm?t=aaaaea00-22&o=9&p=16&l=bn1&mode=books-jp&browse=466304&fc1=000000&lt1=_blank&lc1=3366FF&bg1=FFFFFF&f=ifr"
                    marginwidth="0" marginheight="0" width="468" height="336" border="0" frameborder="0"
                    style="border:none;" scrolling="no"></iframe>


            <img src="/img/top_foot.gif" alt="" width="551" height="2" border="0"/></td>
    </tr>
    <tr>
        <td width="551" height="23" align="right" bgcolor="#23673D" colspan="2">
            <div id="copyright">Copyright (C) 2005 ことば探し. All Rights Reserved.</div>
        </td>
    </tr>
</table>
