</td>
<td width=11><img src="/img/top_leaw.gif" alt="" width="11" height="46" border="0"/></td></tr>
</table>
<!--↑コンテンツ-->
</td>
<td width="21"><img src="/img/top_leax.gif" alt="" width="21" height="110" border="0"/></td>
</tr>
</table>
<!--↑全体-->

<table width="741" border="0" cellspacing="0" cellpadding="0" height="70">
    <tr>
        <td width="190" rowspan="3" valign="bottom"><img src="/img/top_leay2.gif" alt="" width="190"
                                                         height="70" border="0"/></td>
        <td width="275" height="45">
            <div id="topagetop">
                ▼　<a href="/" id="categorylink">「ことば探し」トップページへ</a>
            </div>
        </td>
        <td width="276" height="45">
            <div id="topagetop">
                ▲　<a href="#pagetop" id="categorylink">このページのトップへ</a>
            </div>
        </td>
    </tr>
    <tr>
        <td width="551" height="2" colspan="2">

            <!-- 2009/02/06 広告追加 -->


            <SCRIPT charset="utf-8" type="text/javascript"
                    src="http://ws-fe.amazon-adsystem.com/widgets/q?rt=tf_cw&ServiceVersion=20070822&MarketPlace=JP&ID=V20070822%2FJP%2Faaaaea00-22%2F8010%2F89a00111-27ef-4f57-9253-c940d4549aef&Operation=GetScriptTemplate"></SCRIPT>
            <NOSCRIPT><A rel="nofollow"
                         HREF="http://ws-fe.amazon-adsystem.com/widgets/q?rt=tf_cw&ServiceVersion=20070822&MarketPlace=JP&ID=V20070822%2FJP%2Faaaaea00-22%2F8010%2F89a00111-27ef-4f57-9253-c940d4549aef&Operation=NoScript">Amazon.co.jp
                    ウィジェット</A></NOSCRIPT>


            <img src="/img/top_foot.gif" alt="" width="551" height="2" border="0"/></td>
    </tr>
    <tr>
        <td width="551" height="23" align="right" bgcolor="#23673D" colspan="2">
            <div id="copyright">Copyright (C) 2005 ことば探し. All Rights Reserved.</div>
        </td>
    </tr>
</table>
