</td>
<td width=11><img src="/img/top_leaw.gif" alt="" width="11" height="46" border="0"></td></tr>
</table>
</td>
<td width="160"><img src="/img/top_leax.gif" alt="" width="21" height="110" border="0">
    <div align="center"><span class="sidemenu"><br>『おすすめ本の紹介』</span></div>
    <iframe style="width:120px;height:240px;" marginwidth="0" marginheight="0" scrolling="no" frameborder="0"
            src="https://rcm-fe.amazon-adsystem.com/e/cm?ref=tf_til&t=aaaaea00-22&m=amazon&o=9&p=8&l=as1&IS2=1&detail=1&asins=4837971768&linkId=58aad76f6832a3c3508c398c691709ba&bc1=baf2c5&lt1=_blank&fc1=333333&lc1=0066c0&bg1=baf2c5&f=ifr">
    </iframe>
    <iframe style="width:120px;height:240px;" marginwidth="0" marginheight="0" scrolling="no" frameborder="0"
            src="https://rcm-fe.amazon-adsystem.com/e/cm?ref=tf_til&t=aaaaea00-22&m=amazon&o=9&p=8&l=as1&IS2=1&detail=1&asins=4837972365&linkId=bd4fd1feec0e69857f460a21bd7eef4d&bc1=baf2c5&lt1=_blank&fc1=333333&lc1=0066c0&bg1=baf2c5&f=ifr">
    </iframe>
</td>
</tr>
</table>
