</td><td width=11><img src="<?php echo $URL?>img/top_leaw.gif" alt="" width="11" height="46" border="0" /></td></tr>
</table>
<!--↑コンテンツ-->
</td>
<td width="21"><img src="<?php echo $URL?>img/top_leax.gif" alt="" width="21" height="110" border="0" /></td>
</tr>

<tr valign="bottom">
<td width="741" colspan="3">





<table width="741" border=0 cellspacing="0" cellpadding="0" height="70">
	<tr>
		<td width="190" rowspan="3" valign="bottom"><img src="<?php echo $URL?>img/top_leay2.gif" alt="" width="190" height="70" border="0" /></td>
		<td width="275" height="45">
			<div id="topagetop">
			▼　<a href="<?php echo $URL?>" id="categorylink">「ことば探し」トップページへ</a>
			</div>
		</td>
		<td width="276" height="45">
			<div id="topagetop">
			▲　<a href="#pagetop" id="categorylink">このページのトップへ</a>
			</div>
		</td>
	</tr>
	<tr>
		<td width="551" height="2" colspan="2">
		
		<!-- 2009/02/06 広告追加 -->

<iframe src="http://rcm-fe.amazon-adsystem.com/e/cm?t=aaaaea00-22&o=9&p=16&l=bn1&mode=books-jp&browse=466304&fc1=000000&lt1=_blank&lc1=3366FF&bg1=FFFFFF&f=ifr" marginwidth="0" marginheight="0" width="468" height="336" border="0" frameborder="0" style="border:none;" scrolling="no"></iframe>



		

		<img src="<?php echo $URL?>img/top_foot.gif" alt="" width="551" height="2" border="0" /></td>
	</tr>
	<tr>
		<td width="551" height="23" align="right" bgcolor="#23673D" colspan="2">
			<div id="copyright">Copyright (C) 2005 ことば探し. All Rights Reserved.</div>
		</td>
	</tr>
</table>
