</td>
<td width=11><img src="/img/top_leaw.gif" alt="" width="11" height="46" border="0"/></td></tr>
</table>
<!--↑コンテンツ-->
</td>
<td width="160"><img src="/img/top_leax.gif" alt="" width="21" height="110" border="0"/>
    <br>
    <div align="center"><span class="sidemenu"><br>『おすすめ本の紹介』</span></div>

    <iframe style="width:120px;height:240px;" marginwidth="0" marginheight="0" scrolling="no" frameborder="0"
            src="https://rcm-fe.amazon-adsystem.com/e/cm?ref=tf_til&t=aaaaea00-22&m=amazon&o=9&p=8&l=as1&IS2=1&detail=1&asins=4837971768&linkId=58aad76f6832a3c3508c398c691709ba&bc1=baf2c5&lt1=_blank&fc1=333333&lc1=0066c0&bg1=baf2c5&f=ifr">
    </iframe>
    <br>

    <iframe style="width:120px;height:240px;" marginwidth="0" marginheight="0" scrolling="no" frameborder="0"
            src="https://rcm-fe.amazon-adsystem.com/e/cm?ref=tf_til&t=aaaaea00-22&m=amazon&o=9&p=8&l=as1&IS2=1&detail=1&asins=4837972365&linkId=bd4fd1feec0e69857f460a21bd7eef4d&bc1=baf2c5&lt1=_blank&fc1=333333&lc1=0066c0&bg1=baf2c5&f=ifr">
    </iframe>


    <OBJECT classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000"
            codebase="http://fpdownload.macromedia.com/get/flashplayer/current/swflash.cab"
            id="Player_db988e6d-9ced-4bcd-84af-a7e2c853436e" WIDTH="160px" HEIGHT="600px">
        <PARAM NAME="movie"
               VALUE="http://ws.amazon.co.jp/widgets/q?ServiceVersion=20070822&MarketPlace=JP&ID=V20070822%2FJP%2Faaaaea00-22%2F8010%2Fdb988e6d-9ced-4bcd-84af-a7e2c853436e&Operation=GetDisplayTemplate">
        <PARAM NAME="quality" VALUE="high">
        <PARAM NAME="bgcolor" VALUE="#FFFFFF">
        <PARAM NAME="allowscriptaccess" VALUE="always">
        <embed src="http://ws.amazon.co.jp/widgets/q?ServiceVersion=20070822&MarketPlace=JP&ID=V20070822%2FJP%2Faaaaea00-22%2F8010%2Fdb988e6d-9ced-4bcd-84af-a7e2c853436e&Operation=GetDisplayTemplate"
               id="Player_db988e6d-9ced-4bcd-84af-a7e2c853436e" quality="high" bgcolor="#ffffff"
               name="Player_db988e6d-9ced-4bcd-84af-a7e2c853436e" allowscriptaccess="always"
               type="application/x-shockwave-flash" align="middle" height="600px" width="160px"></embed>
    </OBJECT>
    <NOSCRIPT><A
                HREF="http://ws.amazon.co.jp/widgets/q?ServiceVersion=20070822&MarketPlace=JP&ID=V20070822%2FJP%2Faaaaea00-22%2F8010%2Fdb988e6d-9ced-4bcd-84af-a7e2c853436e&Operation=NoScript">Amazon.co.jp
            ウィジェット</A></NOSCRIPT>


</td>
</tr>
</table>
<!--↑全体-->

<table width="741" border="0"   height="70">
    <tr>
        <td width="190" rowspan="3" valign="bottom"><img src="/img/top_leay2.gif" alt="" width="190"
                                                         height="70" border="0"/></td>
        <td width="275" height="45">
            <div id="topagetop">
                ▼　<a href="/" id="categorylink">「ことば探し」トップページへ</a>
            </div>
        </td>
        <td width="276" height="45">
            <div id="topagetop">
                ▲　<a href="#pagetop" id="categorylink">このページのトップへ</a>
            </div>
        </td>
    </tr>
    <tr>
        <td width="551" height="2" colspan="2">

            <!-- 2009/02/06 広告追加 -->

            <iframe src="http://rcm-fe.amazon-adsystem.com/e/cm?t=aaaaea00-22&o=9&p=293&l=ur1&category=books&f=ifr"
                    width="640" height="100" scrolling="no" border="0" marginwidth="0" style="border:none;"
                    frameborder="0"></iframe>


            <img src="/img/top_foot.gif" alt="" width="551" height="2" border="0"/></td>
    </tr>
    <tr>
        <td width="551" height="23" align="right" bgcolor="#23673D" colspan="2">
            <div id="copyright">Copyright (C) 2005 ことば探し. All Rights Reserved.</div>
        </td>
    </tr>
</table>
