<table border="0" width=0 cellpadding=10 cellspacing=0>
    <tr>
        <td id=kihonbold nowrap><img src=../img/point_ko2.gif alt=width=22 height=17 border="0"><a href=01.php
                                                                                                   id=greenlink>「本の読み方」</a><img
                    src=../img/point_ko2.gif alt=width=22 height=17 border="0"><a href=books.php id=greenlink>「読んでみて！おすすめの本」</a><img
                    src=../img/point_ko.gif alt=width=22 height=17 border="0"><a href=reading.php id=greenlink>「今日のおすすめ本」</a>


            <img src=../img/point_ko.gif alt=width=22 height=17 border="0"><a href=books2.php id=greenlink>「夫婦関係を考えるおすすめ本３３冊」</a>


            <img src=../img/point_ko.gif alt=width=22 height=17 border="0"></td>
    </tr>
</table>
