<?php
require_once '../inc/func.inc';
$CONTENTS_TITLE = "■まゆの「ぼちぼち的」本の読み方＆おすすめの本■<br><span id=kihonbold>～もっと気楽に本を読んでみませんか？世界がひろがりますよ～</span>";
require_once $INC_PATH.'head_set_1column.inc';
?>

<div align=center>

<?require'top_menu.inc';?>

<table border="0" width=700 cellpadding=0 cellspacing=0>
<tr valign=top>
<td width=200 id=kihon>

<?php require_once'yomikata_mokuji.inc';?>

</td>
<td width=30><img src="<?=$URL?>img/1pix0000.gif" alt="" width="30" height="1" border="0" /></td>
<td width=450 id=kihon>
