<?
require_once '../inc/func.inc';
$CONTENTS_TITLE = "■「本から読みとく男女の違い」■<br><span id=kihonbold>～パートナーと、ぼちぼちうまくやっていきませんか？～</span>";
require_once $INC_PATH.'head_set_1column.inc';
?>

<div align=center>

<table border=0 width=0 cellpadding=10 cellspacing=0>
  <tr>
    <td id=kihonbold nowrap><img src=../img/point_ko2.gif alt= width=22 height=17 border=0><a href=01.php id=greenlink>男女の違いについて</a><img src=../img/point_ko2.gif alt= width=22 height=17 border=0><a href=books.php id=greenlink>20冊のおすすめ本</a><img src=../img/point_ko.gif alt= width=22 height=17 border=0><a href=table.php id=greenlink>「一目でわかる男女の比較表」</a><img src=../img/point_ko.gif alt= width=22 height=17 border=0><a href=weekly.php id=greenlink>今週の「男女の違い」</a><img src=../img/point_ko.gif alt= width=22 height=17 border=0></td>
  </tr>
</table>

<table border=0 width=700 cellpadding=0 cellspacing=0>
<tr valign=top>
<td width=200 id=kihon>

<?php require_once'danjyo_mokuji.inc';?>

</td>
<td width=30><img src="<?=$URL?>img/1pix0000.gif" alt="" width="30" height="1" border="0" /></td>
<td width=450 id=kihon>
