<?php
require_once '../inc/func.inc';
$CONTENTS_TITLE = '■「本から読みとく男女の違い」■<br><span id="kihonbold">～パートナーと、ぼちぼちうまくやっていきませんか？～</span>';
require_once $_SERVER["DOCUMENT_ROOT"] . '/inc/html_head.inc';
require_once $_SERVER["DOCUMENT_ROOT"] . '/inc/site_start_1column.inc';
require_once $_SERVER["DOCUMENT_ROOT"] . '/inc/head_set_1column2.inc';
?>
<div>
    <table>
        <tr>
            <td id="kihonbold" nowrap>
                <img src="/img/point_ko2.gif" alt="" width="22" height="17" border="0">
                <a href="01.php" id="greenlink">男女の違いについて</a>
                <img src="/img/point_ko2.gif" alt="" width="22" height="17" border="0">
                <a href="books.php" id="greenlink">20冊のおすすめ本</a>
                <img src="/img/point_ko.gif" alt="" width="22" height="17" border="0">
                <a href="table.php" id="greenlink">「一目でわかる男女の比較表」</a>
                <img src="/img/point_ko.gif" alt="" width="22" height="17" border="0">
                <a href="04.php" id="greenlink">25の行動</a>
                <img src="/img/point_ko.gif" alt="" width="22" height="17" border="0">
            </td>
        </tr>
    </table>

    <table border="0" width="700">
        <tr valign="top">
            <td width="200">
                <?php require_once 'danjyo_mokuji.inc'; ?>
            </td>
            <td width="30"><img src="/img/1pix0000.gif" alt="" width="30" height="1" border="0"></td>
            <td width="450">
