<?php
require_once '../inc/func.inc';
$CONTENTS_TITLE = '■「本から読みとく男女の違い」■<br><span id="kihonbold">～パートナーと、ぼちぼちうまくやっていきませんか？～</span>';
require_once $_SERVER["DOCUMENT_ROOT"] . '/inc/head_set_1column.inc';
?>
<div align="center">
    <table width="0"  >
        <tr>
            <td  bold nowrap>
                <img src="/img/point_ko2.gif" alt="" width="22" height="17">
                <a href="01.php" id="greenlink">男女の違いについて</a>
                <img src="/img/point_ko2.gif" alt="" width="22" height="17">
                <a href="books.php" id="greenlink">20冊のおすすめ本</a>
                <img src="/img/point_ko.gif" alt="" width="22" height="17">
                <a href="table.php" id="greenlink">「一目でわかる男女の比較表」</a>
                <img src="/img/point_ko.gif" alt="" width="22" height="17">
                <a href="weekly.php" id="greenlink">今週の「男女の違い」</a>
                <img src="/img/point_ko.gif" alt="" width="22" height="17">
            </td>
        </tr>
    </table>
    <table width="700"  >
        <tr valign="top">
            <td width="200" >
                <!--↓目次--><br><br>
                <table width=100% cellpadding=2 cellspacing=2>

                    <tr>
                        <td width=1%><img src="../img/point_bo.gif"></td>
                        <td width=99%><a href='01.php' id=yomilink>「男と女の違い」を知ることをおすすめするわけ</a></td>
                    </tr>

                    <tr>
                        <td colspan=2>&nbsp;</td>
                    </tr>

                    <tr>
                        <td width=1%><img src="../img/point_bo.gif"></td>
                        <td width=99%><a href='02.php' id=yomilink>私はパートナーを変えようと努力していました、それが愛と信じて</a></td>
                    </tr>

                    <tr>
                        <td colspan=2>&nbsp;</td>
                    </tr>

                    <tr>
                        <td width=1%><img src="../img/point_bo.gif"></td>
                        <td width=99%><a href='03.php' id=yomilink>「男と女」ってこんなに違うのね…を実感</a></td>
                    </tr>

                    <tr>
                        <td colspan=2>&nbsp;</td>
                    </tr>

                    <tr>
                        <td width=1%><img src="../img/point_bo.gif"></td>
                        <td width=99%><a href='04.php' id=yomilink>私が学んだ「女性が気を配るともっとうまくいく！２５の行動」</a></td>
                    </tr>

                    <tr>
                        <td colspan=2>&nbsp;</td>
                    </tr>

                    <tr>
                        <td width=1%><img src="../img/point_bo.gif"></td>
                        <td width=99%><a href='05.php' id=yomilink>力を抜いて、ぼちぼちうまくやっていきましょう</a></td>
                    </tr>

                    <tr>
                        <td colspan=2>&nbsp;</td>
                    </tr>

                    <tr>
                        <td width=1%><img src="../img/point_bo.gif"></td>
                        <td width=99%><a href='06.php' id=yomilink>お断りとお願い</a></td>
                    </tr>

                </table>
                <!--↑目次-->
            </td>
            <td width="30"><img src="/img/1pix0000.gif" alt="" width="30" height="1"></td>
            <td width="450" >
